// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace pogodynkaV4.Migrations
{
    [DbContext(typeof(RazorPagesGameContext))]
    partial class RazorPagesGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Weather", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("mainWeatherTemp")
                        .HasColumnType("REAL");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("uploadTime")
                        .HasColumnType("INTEGER");

                    b.Property<float>("visibility")
                        .HasColumnType("REAL");

                    b.Property<string>("weatherDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
